name: ChatCitizen
main: org.pale.chatcitizen2.Plugin
version: 2.0.5
api-version: 1.21.4
depend: [Citizens]
commands:
  chatcitizen:
    description: ChatCitizen configuration command
    aliases: [ccz]
    usage: /chatcitizen
    permission: chatcitizen
